it('visits the app', () => {
  cy.visit('/')
})

describe('Home page', () => {
  beforeEach(() => {
    cy.visit('/')
  })
  it('check keypad buttons', () => {
    cy.get('.components__Button-z5xa8-0 exWfJy')
      .contains('0')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('-')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('1')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('+')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('2')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('*')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('3')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('4')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('5')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('6')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('7')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('8')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('9')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('/')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('(')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains(')')
      .click()
      .get('components__Display-sc-18jb73-0 iOZszI')
      .contains('0-1+2*3456789/()')
  })
  it('chek sum', () => {
    cy.get('.components__Button-z5xa8-0 exWfJy')
      .contains('1')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('+')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('1')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('=')
      .click()
      .get('components__Display-sc-18jb73-0 iOZszI')
      .contains('2')
  })
  it('chek div', () => {
    cy.get('.components__Button-z5xa8-0 exWfJy')
      .contains('2')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('/')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('1')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('=')
      .click()
      .get('components__Display-sc-18jb73-0 iOZszI')
      .contains('1')
  })

  it('chek minus', () => {
    cy.get('.components__Button-z5xa8-0 exWfJy')
      .contains('1')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('-')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('1')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('=')
      .click()
      .get('components__Display-sc-18jb73-0 iOZszI')
      .contains('0')
  })
  it('chek multiplication', () => {
    cy.get('.components__Button-z5xa8-0 exWfJy')
      .contains('2')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('*')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('2')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('=')
      .click()
      .get('components__Display-sc-18jb73-0 iOZszI')
      .contains('4')
  })
  it('check calculate', () => {
    cy.get('.components__Button-z5xa8-0 exWfJy')
      .contains('3')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('-')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('1')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('+')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('3')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('*')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('3')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('/')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('(')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('6')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('+')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('9')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains(')')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('=')
      .click()
      .get('components__Display-sc-18jb73-0 iOZszI')
      .contains('1')
  })
  it('clear expression', () => {
    cy.get('.components__Button-z5xa8-0 exWfJy')
      .contains('1')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('-')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('1')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('C')
      .click({ force: true })
      .get('components__Display-sc-18jb73-0 iOZszI')
      .should('have.value', '')
  })

  it('clear element', () => {
    cy.get('.components__Button-z5xa8-0 exWfJy')
      .contains('1')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('-')
      .click({ force: true })
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('1')
      .click()
      .get('.components__Button-z5xa8-0 exWfJy')
      .contains('CE')
      .click()
      .get('components__Display-sc-18jb73-0 iOZszI')
      .contains('1-')
  })
})

describe('Settigns page', () => {
  beforeEach(() => {
    cy.visit('/settigns')
  })
})

it('check clear all histoty', () => {
  cy.visit('/')
    .get('.components__Button-z5xa8-0 exWfJy')
    .contains('1')
    .click()
    .get('.components__Button-z5xa8-0 exWfJy')
    .contains('*')
    .click()
    .get('.components__Button-z5xa8-0 exWfJy')
    .contains('1')
    .click()
    .get('.components__Button-z5xa8-0 exWfJy')
    .contains('=')
    .click()
    .get('components__Display-sc-18jb73-0 iOZszI')
    .contains('1')
    .get('.components__HistoryList-sc-1fjbrha-0 hcxLTI')
    .should('have.length', 1)
    .visit('/settigns')
    .get('.components__Button-spdf8s-2 egCutY')
    .click()
    .visit('/')
    .get('.components__HistoryList-sc-1fjbrha-0 hcxLTI')
    .should('have.length', 0)
})
it('select theme', () => {
  cy.get('.components__ThemeSelector-spdf8s-3 gzxRqe')
    .select('Light theme')
    .should('have.value', 'light')
    .select('Dark theme')
    .should('have.value', 'dark')
})
it('change theme', () => {
  cy.get('.components__ThemeSelector-spdf8s-3 gzxRqe')
    .select('Light theme')
    .should('have.value', 'light')
    .get('.components__Card-spdf8s-0 cXBxji')
    .should(
      'have.css',
      'background-color',
      'rgb(255, 255, 255)',
    )
    .get('.components__ThemeSelector-spdf8s-3 gzxRqe')
    .select('Dark theme')
    .should('have.value', 'dark')
    .get('.components__Card-spdf8s-0 cXBxji')
    .should(
      'have.css',
      'background-color',
      'rgb(0, 0, 0)',
    )
})