export const ACTION_PREFIX = '@/template'
export const SET_EXPRESSION = 'SET_EXPRESSION'
export const CALCULATE = 'CALCULATE'
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY'
export const CLEAR = 'CLEAR'
export const CLEAR_ELEMENT = 'CLEAR_ELEMENT'
export const CLEAR_HISTORY = 'CLEAR_HISTORY'
export const CHANGE_THEME = 'CHANGE_THEME'